faqs:
  {
    'General FAQs': [
      {
        question: 'How much does it cost to join?',
        answer: '<p>£35.00 for the year, entitling you to cheaper socials, jump ticket deals and kit hire rates.</p>',
        weighting: 100
      },
      {
        question: 'How do I join?',
        answer: '<p>We recommend coming along to one of our socials (check the facebook group to find out when and where). After you''ve decided you were right, skydiving is the best idea ever, you can buy membership on the <a href="http://www.leedsuniversityunion.org.uk/groups/skydiving/" title="Skydiving on the Leeds University Union website.">Union page</a>.</p>',
        weighting: 95
      },
      {
        question: 'I''m not quite up for being a solo skydiver just yet, can I do a tandem?',
        answer: '<p>Absolutely, just message a committee member or come along to a social and we''ll try and get you booked in as soon as possible. We do recommend going the solo route, as it''s cheaper and we know you''ll love skydiving as much as we do.</p>',
        weighting: 90
      },
      {
        question: 'Are there any limiting factors?',
        answer: '<p>There is a 16 stone weight limit to do a solo course and 15 stone to do a tandem. You also need a clean bill of health, or a doctor''s permission to jump.</p>',
        weighting: 85
      },
      {
        question: 'Is it safe?',
        answer: '<p>Skydiving is an ''extreme'' sport and with every extreme sport there are risks posed. However, there are measures taken to reduce these risks.</p>
                <p>Our kit is of the highest standard, including easy to use square parachutes, allowing you to land gently and safely.
                It also includes a reserve parachute, there in case your main parachute doesn''t function properly (extremely rare). This reserve parachute is maintained to the highest standard and is repacked every 6 months by a professional packer. Most of the club have never seen a reserve parachute flying over their head, even with hundreds of jumps.
                All kits are also fitted with Automatic Activation Devices, equipment that will deploy your reserve parachute if you aren''t able to. This means if you pass out during freefall, your parachute will be deployed, meaning you can still land safely.</p>
                <p>To be a skydiver, you undergo rigorous training, from ground school (your initial training) to regular briefs. You''ll receive this training until your final jump as a student skydiver, upon which you''ll be rewarded your A-license and be allowed to jump without an instructor. By this time, you''ll be fully trained and will be able to deal with any issues that may arise.</p>
                As much as the media portrays skydivers to be adrenaline junkies and thrill seekers, most of us merely enjoy the sport and wish for nothing more than to land safely after every jump. For more information about the safety of the sport, please visit our governing body''s page:</p>
                <p><a href="http://www.bpa.org.uk/staysafe/how-safe/">BPA - Stay Safe - How Safe?</a></p>',
        weighting: 80
      },
      {
        question: 'Is it expensive?',
        answer: '<p>Not really!</p>
                <p>As a trainee skydiver, your jumps will be no more than £36.00 per skydive and after qualifying, they''ll be considerably less (from £16.00). The fact that we subsidise these prices makes learning to skydive at university the cheapest you will ever get it!</p>
                We also allow you to hire kit through the year, meaning we take care of the expensive maintenance and cost of having your own parachute until you are able to afford it yourself.</p>',
        weighting: 75
      }
    ],
    'RAPs FAQs': [
      {
        question: 'How much does each jump cost?',
        answer: '<p>We aim to subsidise training jumps down to £36.00 and experienced jumps to £16.00 or less this year.</p>',
        weighting: 100
      },
      {
        question: 'How much is the initial training fee?',
        answer: '<p>£175.00 – this includes <strong>two jumps</strong> and all your training!</p>',
        weighting: 95
      },
      {
        question: 'How many jumps will it be until I qualify as an experienced skydiver?',
        answer: '<p>Every person is different and takes a slighly different amount of time to learn to skydive. The minimum is 28 jumps and most people take around 28-35.</p>',
        weighting: 90
      }
    ]
  }
committee: [
  {
    name: 'Rebecca Mansfield',
    role: 'President',
    weighting: 100,
    image: 'committee/mansfield.jpg'
  },
  {
    name: 'Tom Ravet-Bailey',
    role: 'Vice-Captain',
    weighting: 90,
    image: 'committee/ravet_bailey.jpg'
  },
  {
    name: 'Tyler Priestley',
    role: 'RAPs Secretary',
    weighting: 80,
    image: 'committee/priestley.jpg'
  },
  {
    name: 'Bethan Walker',
    role: 'Treasurer',
    weighting: 70,
    image: 'committee/walker.jpg'
  },
  {
    name: 'Emily Aucutt',
    role: 'Kit Secretary',
    weighting: 60,
    image: 'committee/aucutt.jpg'
  },
  {
    name: 'Jack Walker',
    role: 'Social Secretary',
    weighting: 50,
    image: 'committee/walkerj.jpg'
  },
  {
    name: 'Jim Dickinson',
    role: 'Social Secretary',
    weighting: 40,
    image: 'committee/dickinson.jpg'
  },
  {
    name: 'James S-J',
    role: 'Technology Admin',
    weighting: 30,
    image: 'committee/sherwood_jones.jpg'
  }
]
packages: [
  {
    title: 'Static line course (RAPS)',
    description: 'This price includes the whole training course (ground school) and <strong>two</strong> skydives! Mental!',
    price: 175,
    active: true,
    weighting: 100
  },
  {
    title: 'Accelerated Freefall (AFF) Course',
    description: 'Mo instructors, mo money. It''s not really that expensive, TBH IMO...',
    price: 999.99,
    active: true,
    weighting: 90
  },
  {
    title: 'Jump ticket (static line course student)',
    description: 'One jump ticket for a static line student.',
    price: 36,
    active: true,
    weighting: 95,
    requirements: 'You must have completed ground school (Static line course) to use one of these jump tickets.'
  },
  {
    title: 'Tandem skydive',
    description: 'Experience the ultimate thrill with none of the whole "opening your own parachute" bit!!! WOWZERS.',
    price: 230,
    active: true,
    weighting: 90
  },
  {
    title: 'Jump ticket (experienced skydiver)',
    description: 'If you''ve qualified and have your A-license, then this is for you!',
    price: 16,
    active: true,
    weighting: 80
  }
]